### PR TITLE
Proposed fix to Proto aliasing issue

### PR DESCRIPTION
**Pull request by Xliff**
Awaiting review.

### CODE REVIEW

**Comment by lizmat** [comment]
Thanks for this.  But it still feels like it is fixing a problem that is actually a bug in class composition of Rakudo itself.  Also, it looks to me that the code is not thread-safe, using "global" hashes.

I'm pretty tired at the moment.  Your PR is definitely food for thought on researching the class composition in Rakudo.

**Comment by Xliff** [comment]
Yes, this was pointed out to me. I am reworking some of it.

Talk to you soon.

**Comment by vrurg** [comment]
> Thanks for this. But it still feels like it is fixing a problem that is actually a bug in class composition of Rakudo itself. Also, it looks to me that the code is not thread-safe, using "global" hashes.

As I partially participated in this fix, I'd note that there is no race condition in the code. It contains nothing that would be run-time executed. Compile-time is single-threaded anyway. And I don't foresee any plans of changing this.

**Comment by lizmat** [comment]
Multiple threads could do a string EVAL, which both could have a string with "is also" in it.

Unlikely?  Perhaps.  But nonetheless possible.  Or am I missing something?

**Comment by vrurg** [comment]
Possible, but not now. Eval itself isn't thread-safe. It reuses same compiler instance. Though when I experimented with creating a new one it didn't work too.

Though in general I agree with you.

**Comment by lizmat** [comment]
EVAL not being thread-safe, is that a known issue?

**Comment by vrurg** [comment]
Yes. I'm now on my iPad, not easy to find the ticket. But as I remember, it exists.

**Comment by vrurg** [comment]
Ok, found it: rakudo/rakudo#1391

**Comment by lizmat** [comment]
Still think it would need to be fixed in core.  Until then, this fix will do.

**Pull request merged**
